добавил функции согласно задания
htmlacademy-javascript/2325181-kekstagram-28 pull request #2
Opened 2023-02-18 23:36 UTC by cruzr1

1. В файле index.html добавил ссылку на functions.js.
2. В файле functions.js добавил функции: 
- проверка длины строки, 
- проверка палиндрома, 
- извлечение цифр,  
- генерация строки с добавочными символами.

2023-02-19 18:06 UTC, rgusseinov requested changes
Привет!

Функции проверил, работают. Молодец, отличная работа.
Но есть небольшая проблема, линтер ругается на функции. Подробно написал выше.
Например вот: 3:10  error  'isStringLength' is defined but never used  no-unused-vars

Давай исправим это :)

2023-02-19 18:06 UTC, rgusseinov commented on js/functions.js
> +function isStringLength(string, length) {
Линтер ругается что функция создана, но не используется.
Попробуй разобраться с этим, посмотри что можно сделать чтобы ошибок и предупреждении от линтера не было. Можно решить проблему так Наведи курсор мыши на функцию и система подскажет что можно сделать.

2023-02-19 18:06 UTC, rgusseinov commented on js/functions.js
> +function isPalindrom(string) {
Здесь также

2023-02-19 18:06 UTC, rgusseinov commented on js/functions.js
> +function extractNumbers(input) {
И здесь

2023-02-19 18:06 UTC, rgusseinov commented on js/functions.js
> +function concatString(initialString, minimalLength, addSymbols) {
И тут также, как выше описал

2023-02-20 12:19 UTC, cruzr1 commented
Привет!
Спасибо за комментарии! Ошибку с линтером исправил, добавив export в конце файла. Функциональное выражение не стал добавлять, т.к. в code-and-magic функции просто объявлялись. Еще немного подкорректировал функцию concatString, что добавляла остаток добавочных символов в начало строки и добавил параметр в package.json для совместимости с синтаксисом ES6 (иначе node.js ругается на export).

2023-02-21 08:07 UTC, rgusseinov requested changes
Привет, Ринат!

Посмотрел функции, все работает хорошо. Молодец!
Только давай все таки не будем экспортировать их, а просто под объявлением каждой функции сразу ее вызовем с теми аргументами, которые указаны задании.

В таком случае будет проще и не надо будет писать   "type": "module" в package.json. Поскольку могут придраться на проверке потом.

Пока все, исправляй как указал выше и отправляй на проверку.
Удачи!)

2023-02-21 08:08 UTC, rgusseinov commented
> 



> 

Вижу исправил

2023-02-21 08:09 UTC, rgusseinov requested changes
Привет, Ринат!

Посмотрел функции, все работает хорошо. Молодец!
Только давай все таки не будем экспортировать их, а просто под объявлением каждой функции сразу ее вызовем с теми аргументами, которые указаны задании.

В таком случае будет проще и не надо будет писать   "type": "module" в package.json. Поскольку могут придраться на проверке потом.

Пока все, исправляй как указал выше и отправляй на проверку.
Удачи!)

2023-02-21 08:09 UTC, rgusseinov commented on package.json
> +  "type": "module",
Как указал в общем описании, это надо убрать отсюда

2023-02-21 09:22 UTC, cruzr1 commented
Привет, Руслан!
Спасибо, что посмотрел задание! Я убрал экспорт функций и добавил вызовы из задания. В package.json убрал строчку 'type': 'module'.

2023-02-21 18:12 UTC, rgusseinov approved these changes
Привет!

Вот теперь все нормально, отлично.
Двигаемся дальше.

Жду след. ДЗ на проверку.
Удачи!)

2023-02-21 18:12 UTC, merged