Открывается и закрывается часть 1
htmlacademy-javascript/2325181-kekstagram-28 pull request #6
Opened 2023-03-15 08:56 UTC by cruzr1

Привет, Руслан! 

Сделал первую часть ДЗ, написал функцию открытия полноразмерных фото по клику на миниатюры:
1. Подключил новый модуль fullsize.js в точку входа main.js. В него импортировал отрисовку миниатюр и генерацию данных, т.к. для получения комментариев нужны данные сгенерированного списка. И отрисовка миниатюр тоже работает на основе этого списка.
2. Добавил несколько фичей, не описанных в задании: 
 - функция запоминания текущего положения окна (скролла) - крайне актуальна при просмотре на планшете или мобильном, т.к. сайт по умолчанию отбрасывает экран наверх страницы при закрытии полноразмерного окна.
 - функция закрытия полноразмерного окна по клику за пределы области - очень удобно, т.к. не нужно каждый раз тянуться к Esc или крестику в правом верхнем углу.
 - функция добавления/уменьшения лайков при нажатии на соотв. кнопку полноразмерного фото - до конца не доработана, т.к. пока не разобрался, как добавить псевдо-класс, чтобы закрасить значок сердечка. Но количество лайков меняется и передается в миниатюру.

 Есть один момент, который хотел бы обсудить: удаление обработчика, вызывающего функцию скрытия элемента: по идее его нужно удалять внутри самой функции скрытия. Но тут возникает проблема поднятия: по умолчанию я все функции, включая колбэки, оформляю как выражение, присваивая их значение переменной. В таком случае действует ограничение на порядок расположения функций в коде - функция не может быть вызвана до объявления. 
Таким образом, если функция скрытия удаляет обработчик, обращаясь к его колбэку, который описан ниже, программа ругается. Если колбэк, вызывающий функцию скрытия, описан выше, программа тоже ругается. Я решил эту проблему объявив колбэк. Но боюсь, это нарушает критерий Д5, хотя возможно, я неверно его понял. Понимаю, что он не обязательный, но все же, есть ли способ решить эту проблему как-то иначе? Опция однократного использования не помогает, т.к. тогда клик по миниатюре тоже считается событием. 
Кстати, в DevTools я не видел этого обработчика. Может его и не нужно удалять?

С уважением, 
Ринат.

2023-03-16 09:32 UTC, rgusseinov requested changes
Привет!

Проверил ДЗ, отлично, все работает и это главное.
Есть пара пунктов, на которые хотел бы обратить внимание:

- Так лучше не сокращать: socComments. Лучше полностью написать socialComments, иначе придется думать др. человеку. Нужно следить чтобы в др. местах тоже были понятные сокращения.
- Поиск комментариев конкретного поста можно оптимизировать. Сейчас мы бежим по всем циклу из 24 элементов, 
    for(let i = 0; i < descriptionList.length; i++) {
      if (descriptionList[i].id === Number(idNum)) {
        socComments.push(...descriptionList[i].comments);
		
а можно использовать метод массива find чтобы поиск был быстрее. Т.е. он находит элемент по условию и завершается поиск.

Исправляй вышеуказанные пункты и высылай на проверку.
Удачи!)

2023-03-16 09:39 UTC, rgusseinov commented
> Привет, Руслан!
> 
> Сделал первую часть ДЗ, написал функцию открытия полноразмерных фото по клику на миниатюры:
> 
> 1. Подключил новый модуль fullsize.js в точку входа main.js. В него импортировал отрисовку миниатюр и генерацию данных, т.к. для получения комментариев нужны данные сгенерированного списка. И отрисовка миниатюр тоже работает на основе этого списка.
> 2. Добавил несколько фичей, не описанных в задании:
> 
> * функция запоминания текущего положения окна (скролла) - крайне актуальна при просмотре на планшете или мобильном, т.к. сайт по умолчанию отбрасывает экран наверх страницы при закрытии полноразмерного окна.
> * функция закрытия полноразмерного окна по клику за пределы области - очень удобно, т.к. не нужно каждый раз тянуться к Esc или крестику в правом верхнем углу.
> * функция добавления/уменьшения лайков при нажатии на соотв. кнопку полноразмерного фото - до конца не доработана, т.к. пока не разобрался, как добавить псевдо-класс, чтобы закрасить значок сердечка. Но количество лайков меняется и передается в миниатюру.
> 
> Есть один момент, который хотел бы обсудить: удаление обработчика, вызывающего функцию скрытия элемента: по идее его нужно удалять внутри самой функции скрытия. Но тут возникает проблема поднятия: по умолчанию я все функции, включая колбэки, оформляю как выражение, присваивая их значение переменной. В таком случае действует ограничение на порядок расположения функций в коде - функция не может быть вызвана до объявления. Таким образом, если функция скрытия удаляет обработчик, обращаясь к его колбэку, который описан ниже, программа ругается. Если колбэк, вызывающий функцию скрытия, описан выше, программа тоже ругается. Я решил эту проблему объявив колбэк. Но боюсь, это нарушает критерий Д5, хотя возможно, я неверно его понял. Понимаю, что он не обязательный, но все же, есть ли способ решить эту проблему как-то иначе? Опция однократного использования не помогает, т.к. тогда клик по миниатюре тоже считается событием. Кстати, в DevTools я не видел этого обработчика. Может его и не нужно удалять?
> 
> С уважением, Ринат.
> 
> 🎓 [Открывается и закрывается](https://up.htmlacademy.ru/javascript/28/user/2325181/tasks/13)

Ринат, привет еще раз!

Насчет полезных фичей - молодец что обращаешь на это внимание, в дальнейшем пригодится, удобство очень важно. Но тут главное не тратить больше времени на доп. задания, чтобы успеть сделать основное.
По поводу обработчиков, критерии  Д5 больше про то что нельзя смешивать типа обработчиков. В одном проекте можно использовать сделочные и обычные функции например. Сейчас мы проверяем по ТЗ и базовым критериям, на пред. защите будем проверять и по доп. критериям еще.
А так, пока все хорошо.

2023-03-16 12:26 UTC, cruzr1 commented
Привет, Руслан!

Большое спасибо за проверку и комментарии! Исправил название переменной и сделал поиск комментариев через find. 
Насчет обработчиков тогда не буду дальше углубляться, перейду к следующему заданию. Спасибо, что поддержал насчет фичей! 😄  В будущем постараюсь не увлекаться допами, сосредоточусь на соответствии ТЗ.
Еще раз спасибо и хорошего дня! 👍

2023-03-18 09:47 UTC, rgusseinov approved these changes
Привет, Ринат!

Отлично, ДЗ выполнено.

Жду след. ДЗ на проверку.
Удачи!)

2023-03-18 09:47 UTC, merged