добавил функционал загрузки фото
htmlacademy-javascript/2325181-kekstagram-28 pull request #8
Opened 2023-03-23 12:03 UTC by cruzr1

Привет, Руслан!

Сделал новое ДЗ "Правда или действие". Добавил функционал работы с формой загрузки нового изображения: открытие формы после выбора файла, валидация полей хэштегов и комментариев с помощью валидаторов Pristine, появление сообщений об успешной отправке или об ошибке после события Submit. Сами данные пока на сервер не отправляются, но в случае действия по умолчанию от сервера приходит подтверждение об успешной отправке. Все формы закрываются по нажатию кнопок и клавиш Escape.
Немного оптимизировал функции закрытия окон, сократил повторение кода. Но можно еще поработать над этим, например объединить функции по работе с сообщениями об ошибке и успешной отправке.
Спасибо за подсказку по обработчикам! Действительно, можно быстро найти обработчики для конкретного элемента. Пока дорабатывал код, столкнулся с тем, что обработчик keydown не работает на модальных окна сообщений и формы редактирования, только на Document. Пробовал разные методы: и .focus(), и capture и stopPropagation - во всех случаях реагирует на событие только на уровне Document. Никак не могу только понять, почему так происходит?
Подскажи пожалуйста, есть ли какие-то переменные или функции, наименования которых можно было бы сделать более понятными?
Что-то еще можно было бы улучшить в моем коде?

Заранее благодарен!

С уважением,
Ринат.

2023-03-25 05:10 UTC, rgusseinov requested changes
Привет, Ринат!

Проверил ДЗ. В целом все хорошо, код написан чисто и аккуратно.
Молодец что обращаешь внимание на мелочи, например не закрывать форму если пользователь в фокусе поле ввода итд.

Только заметил 1 пункт из ТЗ, который нам нужно поправить/доработать.

- Не полностью реализован пункт ТЗ 1.1. Загрузка нового изображения. 
А именно:
- изменение масштаба изображения;
- применение одного из заранее заготовленных эффектов;
- выбор глубины эффекта с помощью ползунка;

Пока все.
Исправляй вышеуказанные пункты и высылай на проверку.
Удачи!)

2023-03-25 05:23 UTC, rgusseinov commented
> вке или об ошибке после события Submit. Сами данные пока на сервер не отправляются, но в случае действия по умолчанию от сервера приходит подтверждение об успешной отправке. Все формы закрываются по нажатию кнопок и клавиш Escape.

Привет еще раз!)

Да, пока отправку данных на сервер мы не трогаем. Кстати тема сети будет в след. уроке.
Там мы будем получать ответ от сервера и показывать сообщение пользователю.

Вообще, на практике обычно вещают события keydown и keyup на сам документ, ну так надежнее.
Потому-что элементы могут перерисоваться, а обработчики слетят. А на документе они будут висеть.

По поводу улучшения и правильного именования - в целом я сейчас проверяю на понятность названии функции и переменных. Но в основном проверка идет на пункты ТЗ и базовые критерии,
чтобы работало и функционировало. На этапе допуска к защите, я буду проверять не только по ТЗ но и по всем критериям. Там займемся исправлением. А если времени не хватит, то потом мне напомни, я так от себя проверю и дам обратный отзыв. 

Договорились?)

2023-03-28 09:23 UTC, cruzr1 commented
Привет, Руслан!

Еще раз большое спасибо за проверку ДЗ! 👍 Добавил управление масштабом и применение эффекта (включая изменение глубины эффекта с помощью слайдера).
Эта функциональность относится к следующему ДЗ (9.16 Помощь друга). Если мы ее реализуем в этом ДЗ (9.14 Правда или действие), могу ли я в следующем, просто продублировать код с небольшими доработками?
Также я добавил отправку данных формы методом submit()  - это п. 7 ДЗ 9.14.

С уважением, 
Ринат. 😃

2023-03-29 11:23 UTC, rgusseinov commented
> Привет, Руслан!
> 
> Еще раз большое спасибо за проверку ДЗ! 👍 Добавил управление масштабом и применение эффекта (включая изменение глубины эффекта с помощью слайдера). Эта функциональность относится к следующему ДЗ (9.16 Помощь друга). Если мы ее реализуем в этом ДЗ (9.14 Правда или действие), могу ли я в следующем, просто продублировать код с небольшими доработками? Также я добавил отправку данных формы методом submit() - это п. 7 ДЗ 9.14.
> 
> С уважением, Ринат. 😃

Привет, Ринат!

Да, вижу что эффекты добавил.
Ничего страшного, пусть будут. В след. ветке не буду проверять этот пункт ТЗ.
В остальном все хорошо.
Молодец!)

2023-03-29 11:24 UTC, merged